[binding_model=by_value, include="complex.h"] class Complex {
  Complex();
  int download(std::string url, std::string savepath, std::string filename);
  int DirExist(std::string path);
  int makeDirs(std::string path);
  int deleteFile(std::string path, std::string filename);
  int FileExist(std::string path, std::string filename);
  std::string getNonFilename(std::string path, std::string filename);
  std::string getDesktop();
  std::string selectDir();
  float getNowPer();
  int getNowSize();
  int getFileSize();
  int getCancelFlag();
  void setNowPer(float value);
  void setNowSize(int value);
  void setFileSize(int value);
  void setCancelFlag(int value);
};
